### ISSUE TITLE
Possibility to set log file permissions?

### ISSUE THREAD

**Issue by kramer65** [snowzach/rotatefilehook#1]
Is there a way to set the log file permissions? I currently first create the file using os.OpenFile to make sure it has the permissions I need it to have. Is there a way of doing this directly using rotatefilehook?

**Comment by snowzach** [comment]
Hey @kramer65 essentially this is a wrapper around https://github.com/natefinch/lumberjack and their response to that question is to basically do what you already are. https://github.com/natefinch/lumberjack/issues/82 If you want to lobby lumberjack to add this functionality, I'll happily expose it. Sorry for the delay.
